//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManagementSystem.Web.CompanyWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class Companies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAdressField;
        
        private int NumOfVehicleField;
        
        private System.Nullable<int> CompanyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Vehicles[] VehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Employees[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string CompanyEmail {
            get {
                return this.CompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailField, value) != true)) {
                    this.CompanyEmailField = value;
                    this.RaisePropertyChanged("CompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string CompanyCity {
            get {
                return this.CompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCityField, value) != true)) {
                    this.CompanyCityField = value;
                    this.RaisePropertyChanged("CompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string CompanyAdress {
            get {
                return this.CompanyAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAdressField, value) != true)) {
                    this.CompanyAdressField = value;
                    this.RaisePropertyChanged("CompanyAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        internal int NumOfVehicle {
            get {
                return this.NumOfVehicleField;
            }
            set {
                if ((this.NumOfVehicleField.Equals(value) != true)) {
                    this.NumOfVehicleField = value;
                    this.RaisePropertyChanged("NumOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal System.Nullable<int> CompanyPoints {
            get {
                return this.CompanyPointsField;
            }
            set {
                if ((this.CompanyPointsField.Equals(value) != true)) {
                    this.CompanyPointsField = value;
                    this.RaisePropertyChanged("CompanyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Vehicles[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Employees[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class Vehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        private int VehiclesInstantKmField;
        
        private bool HasAirbagField;
        
        private int TrunkVolumeField;
        
        private int SeatingCapacityField;
        
        private decimal DailyRentalPriceField;
        
        private int AgeLimitForDrivingThisCarField;
        
        private int KmLimitPerDayField;
        
        private int RequiredDrivingLicenseAgeField;
        
        private System.DateTime IsAvailableAtTimeField;
        
        private int VehiclesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal int VehiclesInstantKm {
            get {
                return this.VehiclesInstantKmField;
            }
            set {
                if ((this.VehiclesInstantKmField.Equals(value) != true)) {
                    this.VehiclesInstantKmField = value;
                    this.RaisePropertyChanged("VehiclesInstantKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        internal int TrunkVolume {
            get {
                return this.TrunkVolumeField;
            }
            set {
                if ((this.TrunkVolumeField.Equals(value) != true)) {
                    this.TrunkVolumeField = value;
                    this.RaisePropertyChanged("TrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        internal int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal decimal DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        internal int AgeLimitForDrivingThisCar {
            get {
                return this.AgeLimitForDrivingThisCarField;
            }
            set {
                if ((this.AgeLimitForDrivingThisCarField.Equals(value) != true)) {
                    this.AgeLimitForDrivingThisCarField = value;
                    this.RaisePropertyChanged("AgeLimitForDrivingThisCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        internal int KmLimitPerDay {
            get {
                return this.KmLimitPerDayField;
            }
            set {
                if ((this.KmLimitPerDayField.Equals(value) != true)) {
                    this.KmLimitPerDayField = value;
                    this.RaisePropertyChanged("KmLimitPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        internal int RequiredDrivingLicenseAge {
            get {
                return this.RequiredDrivingLicenseAgeField;
            }
            set {
                if ((this.RequiredDrivingLicenseAgeField.Equals(value) != true)) {
                    this.RequiredDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("RequiredDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        internal System.DateTime IsAvailableAtTime {
            get {
                return this.IsAvailableAtTimeField;
            }
            set {
                if ((this.IsAvailableAtTimeField.Equals(value) != true)) {
                    this.IsAvailableAtTimeField = value;
                    this.RaisePropertyChanged("IsAvailableAtTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        internal int VehiclesCompanyId {
            get {
                return this.VehiclesCompanyIdField;
            }
            set {
                if ((this.VehiclesCompanyIdField.Equals(value) != true)) {
                    this.VehiclesCompanyIdField = value;
                    this.RaisePropertyChanged("VehiclesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeesIdField;
        
        private int EmployeesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployessPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Companies EmployeesCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int EmployeesId {
            get {
                return this.EmployeesIdField;
            }
            set {
                if ((this.EmployeesIdField.Equals(value) != true)) {
                    this.EmployeesIdField = value;
                    this.RaisePropertyChanged("EmployeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal int EmployeesCompanyId {
            get {
                return this.EmployeesCompanyIdField;
            }
            set {
                if ((this.EmployeesCompanyIdField.Equals(value) != true)) {
                    this.EmployeesCompanyIdField = value;
                    this.RaisePropertyChanged("EmployeesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string EmployeesEmail {
            get {
                return this.EmployeesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesEmailField, value) != true)) {
                    this.EmployeesEmailField = value;
                    this.RaisePropertyChanged("EmployeesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string EmployessPassword {
            get {
                return this.EmployessPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployessPasswordField, value) != true)) {
                    this.EmployessPasswordField = value;
                    this.RaisePropertyChanged("EmployessPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string EmployeesPhoneNumber {
            get {
                return this.EmployeesPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesPhoneNumberField, value) != true)) {
                    this.EmployeesPhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeesPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string EmployeesAddress {
            get {
                return this.EmployeesAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesAddressField, value) != true)) {
                    this.EmployeesAddressField = value;
                    this.RaisePropertyChanged("EmployeesAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Companies EmployeesCompany {
            get {
                return this.EmployeesCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesCompanyField, value) != true)) {
                    this.EmployeesCompanyField = value;
                    this.RaisePropertyChanged("EmployeesCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalRequests", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class RentalRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentalRequestIdField;
        
        private int RentalRequestCustomerIdField;
        
        private int RequestedSupplierCompanyIdField;
        
        private int RequestedVehicleIdField;
        
        private System.DateTime RequestedPickUpDateField;
        
        private System.DateTime RequestedDropOffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Customers RentalRequestCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Companies RequestedSupplierCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Vehicles RequestedVehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int RentalRequestId {
            get {
                return this.RentalRequestIdField;
            }
            set {
                if ((this.RentalRequestIdField.Equals(value) != true)) {
                    this.RentalRequestIdField = value;
                    this.RaisePropertyChanged("RentalRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal int RentalRequestCustomerId {
            get {
                return this.RentalRequestCustomerIdField;
            }
            set {
                if ((this.RentalRequestCustomerIdField.Equals(value) != true)) {
                    this.RentalRequestCustomerIdField = value;
                    this.RaisePropertyChanged("RentalRequestCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal int RequestedSupplierCompanyId {
            get {
                return this.RequestedSupplierCompanyIdField;
            }
            set {
                if ((this.RequestedSupplierCompanyIdField.Equals(value) != true)) {
                    this.RequestedSupplierCompanyIdField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal int RequestedVehicleId {
            get {
                return this.RequestedVehicleIdField;
            }
            set {
                if ((this.RequestedVehicleIdField.Equals(value) != true)) {
                    this.RequestedVehicleIdField = value;
                    this.RaisePropertyChanged("RequestedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal System.DateTime RequestedPickUpDate {
            get {
                return this.RequestedPickUpDateField;
            }
            set {
                if ((this.RequestedPickUpDateField.Equals(value) != true)) {
                    this.RequestedPickUpDateField = value;
                    this.RaisePropertyChanged("RequestedPickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        internal System.DateTime RequestedDropOffDate {
            get {
                return this.RequestedDropOffDateField;
            }
            set {
                if ((this.RequestedDropOffDateField.Equals(value) != true)) {
                    this.RequestedDropOffDateField = value;
                    this.RaisePropertyChanged("RequestedDropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Customers RentalRequestCustomer {
            get {
                return this.RentalRequestCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestCustomerField, value) != true)) {
                    this.RentalRequestCustomerField = value;
                    this.RaisePropertyChanged("RentalRequestCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Companies RequestedSupplierCompany {
            get {
                return this.RequestedSupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedSupplierCompanyField, value) != true)) {
                    this.RequestedSupplierCompanyField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Vehicles RequestedVehicle {
            get {
                return this.RequestedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedVehicleField, value) != true)) {
                    this.RequestedVehicleField = value;
                    this.RaisePropertyChanged("RequestedVehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedVehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class RentedVehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentIdField;
        
        private int RentedVehicleIdField;
        
        private int SupplierCompanyIdField;
        
        private int DriverCustomerIdField;
        
        private System.DateTime PickUpDateField;
        
        private System.DateTime DropOffDateField;
        
        private int VehiclesPickUpKmField;
        
        private int VehiclesDropOffKmField;
        
        private decimal RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Customers DriverCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Vehicles RentedVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.Companies SupplierCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int RentId {
            get {
                return this.RentIdField;
            }
            set {
                if ((this.RentIdField.Equals(value) != true)) {
                    this.RentIdField = value;
                    this.RaisePropertyChanged("RentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int RentedVehicleId {
            get {
                return this.RentedVehicleIdField;
            }
            set {
                if ((this.RentedVehicleIdField.Equals(value) != true)) {
                    this.RentedVehicleIdField = value;
                    this.RaisePropertyChanged("RentedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int SupplierCompanyId {
            get {
                return this.SupplierCompanyIdField;
            }
            set {
                if ((this.SupplierCompanyIdField.Equals(value) != true)) {
                    this.SupplierCompanyIdField = value;
                    this.RaisePropertyChanged("SupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal int DriverCustomerId {
            get {
                return this.DriverCustomerIdField;
            }
            set {
                if ((this.DriverCustomerIdField.Equals(value) != true)) {
                    this.DriverCustomerIdField = value;
                    this.RaisePropertyChanged("DriverCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        internal System.DateTime DropOffDate {
            get {
                return this.DropOffDateField;
            }
            set {
                if ((this.DropOffDateField.Equals(value) != true)) {
                    this.DropOffDateField = value;
                    this.RaisePropertyChanged("DropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        internal int VehiclesPickUpKm {
            get {
                return this.VehiclesPickUpKmField;
            }
            set {
                if ((this.VehiclesPickUpKmField.Equals(value) != true)) {
                    this.VehiclesPickUpKmField = value;
                    this.RaisePropertyChanged("VehiclesPickUpKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal int VehiclesDropOffKm {
            get {
                return this.VehiclesDropOffKmField;
            }
            set {
                if ((this.VehiclesDropOffKmField.Equals(value) != true)) {
                    this.VehiclesDropOffKmField = value;
                    this.RaisePropertyChanged("VehiclesDropOffKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        internal decimal RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Customers DriverCustomer {
            get {
                return this.DriverCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverCustomerField, value) != true)) {
                    this.DriverCustomerField = value;
                    this.RaisePropertyChanged("DriverCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Vehicles RentedVehicle {
            get {
                return this.RentedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehicleField, value) != true)) {
                    this.RentedVehicleField = value;
                    this.RaisePropertyChanged("RentedVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        internal CarRentalManagementSystem.Web.CompanyWebService.Companies SupplierCompany {
            get {
                return this.SupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCompanyField, value) != true)) {
                    this.SupplierCompanyField = value;
                    this.RaisePropertyChanged("SupplierCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string CustomerPhoneNumber {
            get {
                return this.CustomerPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNumberField, value) != true)) {
                    this.CustomerPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        internal string SecondPhoneNumber {
            get {
                return this.SecondPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPhoneNumberField, value) != true)) {
                    this.SecondPhoneNumberField = value;
                    this.RaisePropertyChanged("SecondPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal string NationalIdcard {
            get {
                return this.NationalIdcardField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdcardField, value) != true)) {
                    this.NationalIdcardField = value;
                    this.RaisePropertyChanged("NationalIdcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        internal CarRentalManagementSystem.Web.CompanyWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyWebService.CompanyWebServiceSoap")]
    internal interface CompanyWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsCompany", ReplyAction="*")]
        CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse SignUpAsCompany(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse> SignUpAsCompanyAsync(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki email öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsCompany", ReplyAction="*")]
        CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse LogInAsCompany(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse> LogInAsCompanyAsync(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCompanyAccount", ReplyAction="*")]
        bool DeleteCompanyAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCompanyAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCompanyAccountAsync(int id);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse UpdateAccount(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetAllCompaniesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCompanies", ReplyAction="*")]
        CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse GetAllCompanies(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCompanies", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse> GetAllCompaniesAsync(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCompanyInformationByIDResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyInformationByID", ReplyAction="*")]
        CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse GetCompanyInformationByID(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyInformationByID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse> GetCompanyInformationByIDAsync(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SignUpAsCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsCompany", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequestBody Body;
        
        public SignUpAsCompanyRequest() {
        }
        
        public SignUpAsCompanyRequest(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SignUpAsCompanyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.Companies entity;
        
        public SignUpAsCompanyRequestBody() {
        }
        
        public SignUpAsCompanyRequestBody(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SignUpAsCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponseBody Body;
        
        public SignUpAsCompanyResponse() {
        }
        
        public SignUpAsCompanyResponse(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class SignUpAsCompanyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignUpAsCompanyResult;
        
        public SignUpAsCompanyResponseBody() {
        }
        
        public SignUpAsCompanyResponseBody(bool SignUpAsCompanyResult) {
            this.SignUpAsCompanyResult = SignUpAsCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LogInAsCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsCompany", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequestBody Body;
        
        public LogInAsCompanyRequest() {
        }
        
        public LogInAsCompanyRequest(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class LogInAsCompanyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInAsCompanyRequestBody() {
        }
        
        public LogInAsCompanyRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LogInAsCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponseBody Body;
        
        public LogInAsCompanyResponse() {
        }
        
        public LogInAsCompanyResponse(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class LogInAsCompanyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInAsCompanyResult;
        
        public LogInAsCompanyResponseBody() {
        }
        
        public LogInAsCompanyResponseBody(bool LogInAsCompanyResult) {
            this.LogInAsCompanyResult = LogInAsCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class UpdateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccount", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequestBody Body;
        
        public UpdateAccountRequest() {
        }
        
        public UpdateAccountRequest(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class UpdateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.Companies entity;
        
        public UpdateAccountRequestBody() {
        }
        
        public UpdateAccountRequestBody(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class UpdateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponseBody Body;
        
        public UpdateAccountResponse() {
        }
        
        public UpdateAccountResponse(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class UpdateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateAccountResult;
        
        public UpdateAccountResponseBody() {
        }
        
        public UpdateAccountResponseBody(bool UpdateAccountResult) {
            this.UpdateAccountResult = UpdateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetAllCompaniesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCompanies", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequestBody Body;
        
        public GetAllCompaniesRequest() {
        }
        
        public GetAllCompaniesRequest(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetAllCompaniesRequestBody {
        
        public GetAllCompaniesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetAllCompaniesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCompaniesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponseBody Body;
        
        public GetAllCompaniesResponse() {
        }
        
        public GetAllCompaniesResponse(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetAllCompaniesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.Companies[] GetAllCompaniesResult;
        
        public GetAllCompaniesResponseBody() {
        }
        
        public GetAllCompaniesResponseBody(CarRentalManagementSystem.Web.CompanyWebService.Companies[] GetAllCompaniesResult) {
            this.GetAllCompaniesResult = GetAllCompaniesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetCompanyInformationByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyInformationByID", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequestBody Body;
        
        public GetCompanyInformationByIDRequest() {
        }
        
        public GetCompanyInformationByIDRequest(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetCompanyInformationByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCompanyInformationByIDRequestBody() {
        }
        
        public GetCompanyInformationByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetCompanyInformationByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyInformationByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponseBody Body;
        
        public GetCompanyInformationByIDResponse() {
        }
        
        public GetCompanyInformationByIDResponse(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetCompanyInformationByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CompanyWebService.Companies GetCompanyInformationByIDResult;
        
        public GetCompanyInformationByIDResponseBody() {
        }
        
        public GetCompanyInformationByIDResponseBody(CarRentalManagementSystem.Web.CompanyWebService.Companies GetCompanyInformationByIDResult) {
            this.GetCompanyInformationByIDResult = GetCompanyInformationByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface CompanyWebServiceSoapChannel : CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class CompanyWebServiceSoapClient : System.ServiceModel.ClientBase<CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap>, CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap {
        
        public CompanyWebServiceSoapClient() {
        }
        
        public CompanyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.SignUpAsCompany(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest request) {
            return base.Channel.SignUpAsCompany(request);
        }
        
        public bool SignUpAsCompany(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse retVal = ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).SignUpAsCompany(inValue);
            return retVal.Body.SignUpAsCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse> CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.SignUpAsCompanyAsync(CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest request) {
            return base.Channel.SignUpAsCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyResponse> SignUpAsCompanyAsync(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.SignUpAsCompanyRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).SignUpAsCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.LogInAsCompany(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest request) {
            return base.Channel.LogInAsCompany(request);
        }
        
        public bool LogInAsCompany(string email, string password) {
            CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse retVal = ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).LogInAsCompany(inValue);
            return retVal.Body.LogInAsCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse> CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.LogInAsCompanyAsync(CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest request) {
            return base.Channel.LogInAsCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyResponse> LogInAsCompanyAsync(string email, string password) {
            CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.LogInAsCompanyRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).LogInAsCompanyAsync(inValue);
        }
        
        public bool DeleteCompanyAccount(int id) {
            return base.Channel.DeleteCompanyAccount(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCompanyAccountAsync(int id) {
            return base.Channel.DeleteCompanyAccountAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.UpdateAccount(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public bool UpdateAccount(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse retVal = ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).UpdateAccount(inValue);
            return retVal.Body.UpdateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse> CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.UpdateAccountAsync(CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.CompanyWebService.Companies entity) {
            CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).UpdateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.GetAllCompanies(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest request) {
            return base.Channel.GetAllCompanies(request);
        }
        
        public CarRentalManagementSystem.Web.CompanyWebService.Companies[] GetAllCompanies() {
            CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequestBody();
            CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse retVal = ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).GetAllCompanies(inValue);
            return retVal.Body.GetAllCompaniesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse> CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.GetAllCompaniesAsync(CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest request) {
            return base.Channel.GetAllCompaniesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesResponse> GetAllCompaniesAsync() {
            CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.GetAllCompaniesRequestBody();
            return ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).GetAllCompaniesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.GetCompanyInformationByID(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest request) {
            return base.Channel.GetCompanyInformationByID(request);
        }
        
        public CarRentalManagementSystem.Web.CompanyWebService.Companies GetCompanyInformationByID(int id) {
            CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequestBody();
            inValue.Body.id = id;
            CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse retVal = ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).GetCompanyInformationByID(inValue);
            return retVal.Body.GetCompanyInformationByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse> CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap.GetCompanyInformationByIDAsync(CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest request) {
            return base.Channel.GetCompanyInformationByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDResponse> GetCompanyInformationByIDAsync(int id) {
            CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest inValue = new CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CompanyWebService.GetCompanyInformationByIDRequestBody();
            inValue.Body.id = id;
            return ((CarRentalManagementSystem.Web.CompanyWebService.CompanyWebServiceSoap)(this)).GetCompanyInformationByIDAsync(inValue);
        }
    }
}
