//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManagementSystem.Web.VehicleWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        private int VehiclesInstantKmField;
        
        private bool HasAirbagField;
        
        private int TrunkVolumeField;
        
        private int SeatingCapacityField;
        
        private decimal DailyRentalPriceField;
        
        private int AgeLimitForDrivingThisCarField;
        
        private int KmLimitPerDayField;
        
        private int RequiredDrivingLicenseAgeField;
        
        private System.DateTime IsAvailableAtTimeField;
        
        private int VehiclesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int VehiclesInstantKm {
            get {
                return this.VehiclesInstantKmField;
            }
            set {
                if ((this.VehiclesInstantKmField.Equals(value) != true)) {
                    this.VehiclesInstantKmField = value;
                    this.RaisePropertyChanged("VehiclesInstantKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TrunkVolume {
            get {
                return this.TrunkVolumeField;
            }
            set {
                if ((this.TrunkVolumeField.Equals(value) != true)) {
                    this.TrunkVolumeField = value;
                    this.RaisePropertyChanged("TrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AgeLimitForDrivingThisCar {
            get {
                return this.AgeLimitForDrivingThisCarField;
            }
            set {
                if ((this.AgeLimitForDrivingThisCarField.Equals(value) != true)) {
                    this.AgeLimitForDrivingThisCarField = value;
                    this.RaisePropertyChanged("AgeLimitForDrivingThisCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int KmLimitPerDay {
            get {
                return this.KmLimitPerDayField;
            }
            set {
                if ((this.KmLimitPerDayField.Equals(value) != true)) {
                    this.KmLimitPerDayField = value;
                    this.RaisePropertyChanged("KmLimitPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int RequiredDrivingLicenseAge {
            get {
                return this.RequiredDrivingLicenseAgeField;
            }
            set {
                if ((this.RequiredDrivingLicenseAgeField.Equals(value) != true)) {
                    this.RequiredDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("RequiredDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime IsAvailableAtTime {
            get {
                return this.IsAvailableAtTimeField;
            }
            set {
                if ((this.IsAvailableAtTimeField.Equals(value) != true)) {
                    this.IsAvailableAtTimeField = value;
                    this.RaisePropertyChanged("IsAvailableAtTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int VehiclesCompanyId {
            get {
                return this.VehiclesCompanyIdField;
            }
            set {
                if ((this.VehiclesCompanyIdField.Equals(value) != true)) {
                    this.VehiclesCompanyIdField = value;
                    this.RaisePropertyChanged("VehiclesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalRequests", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentalRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentalRequestIdField;
        
        private int RentalRequestCustomerIdField;
        
        private int RequestedSupplierCompanyIdField;
        
        private int RequestedVehicleIdField;
        
        private System.DateTime RequestedPickUpDateField;
        
        private System.DateTime RequestedDropOffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Customers RentalRequestCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Companies RequestedSupplierCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Vehicles RequestedVehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentalRequestId {
            get {
                return this.RentalRequestIdField;
            }
            set {
                if ((this.RentalRequestIdField.Equals(value) != true)) {
                    this.RentalRequestIdField = value;
                    this.RaisePropertyChanged("RentalRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RentalRequestCustomerId {
            get {
                return this.RentalRequestCustomerIdField;
            }
            set {
                if ((this.RentalRequestCustomerIdField.Equals(value) != true)) {
                    this.RentalRequestCustomerIdField = value;
                    this.RaisePropertyChanged("RentalRequestCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestedSupplierCompanyId {
            get {
                return this.RequestedSupplierCompanyIdField;
            }
            set {
                if ((this.RequestedSupplierCompanyIdField.Equals(value) != true)) {
                    this.RequestedSupplierCompanyIdField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestedVehicleId {
            get {
                return this.RequestedVehicleIdField;
            }
            set {
                if ((this.RequestedVehicleIdField.Equals(value) != true)) {
                    this.RequestedVehicleIdField = value;
                    this.RaisePropertyChanged("RequestedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime RequestedPickUpDate {
            get {
                return this.RequestedPickUpDateField;
            }
            set {
                if ((this.RequestedPickUpDateField.Equals(value) != true)) {
                    this.RequestedPickUpDateField = value;
                    this.RaisePropertyChanged("RequestedPickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime RequestedDropOffDate {
            get {
                return this.RequestedDropOffDateField;
            }
            set {
                if ((this.RequestedDropOffDateField.Equals(value) != true)) {
                    this.RequestedDropOffDateField = value;
                    this.RaisePropertyChanged("RequestedDropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.VehicleWebService.Customers RentalRequestCustomer {
            get {
                return this.RentalRequestCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestCustomerField, value) != true)) {
                    this.RentalRequestCustomerField = value;
                    this.RaisePropertyChanged("RentalRequestCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRentalManagementSystem.Web.VehicleWebService.Companies RequestedSupplierCompany {
            get {
                return this.RequestedSupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedSupplierCompanyField, value) != true)) {
                    this.RequestedSupplierCompanyField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles RequestedVehicle {
            get {
                return this.RequestedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedVehicleField, value) != true)) {
                    this.RequestedVehicleField = value;
                    this.RaisePropertyChanged("RequestedVehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedVehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentedVehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentIdField;
        
        private int RentedVehicleIdField;
        
        private int SupplierCompanyIdField;
        
        private int DriverCustomerIdField;
        
        private System.DateTime PickUpDateField;
        
        private System.DateTime DropOffDateField;
        
        private int VehiclesPickUpKmField;
        
        private int VehiclesDropOffKmField;
        
        private decimal RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Customers DriverCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Vehicles RentedVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Companies SupplierCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentId {
            get {
                return this.RentIdField;
            }
            set {
                if ((this.RentIdField.Equals(value) != true)) {
                    this.RentIdField = value;
                    this.RaisePropertyChanged("RentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentedVehicleId {
            get {
                return this.RentedVehicleIdField;
            }
            set {
                if ((this.RentedVehicleIdField.Equals(value) != true)) {
                    this.RentedVehicleIdField = value;
                    this.RaisePropertyChanged("RentedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierCompanyId {
            get {
                return this.SupplierCompanyIdField;
            }
            set {
                if ((this.SupplierCompanyIdField.Equals(value) != true)) {
                    this.SupplierCompanyIdField = value;
                    this.RaisePropertyChanged("SupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DriverCustomerId {
            get {
                return this.DriverCustomerIdField;
            }
            set {
                if ((this.DriverCustomerIdField.Equals(value) != true)) {
                    this.DriverCustomerIdField = value;
                    this.RaisePropertyChanged("DriverCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DropOffDate {
            get {
                return this.DropOffDateField;
            }
            set {
                if ((this.DropOffDateField.Equals(value) != true)) {
                    this.DropOffDateField = value;
                    this.RaisePropertyChanged("DropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehiclesPickUpKm {
            get {
                return this.VehiclesPickUpKmField;
            }
            set {
                if ((this.VehiclesPickUpKmField.Equals(value) != true)) {
                    this.VehiclesPickUpKmField = value;
                    this.RaisePropertyChanged("VehiclesPickUpKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int VehiclesDropOffKm {
            get {
                return this.VehiclesDropOffKmField;
            }
            set {
                if ((this.VehiclesDropOffKmField.Equals(value) != true)) {
                    this.VehiclesDropOffKmField = value;
                    this.RaisePropertyChanged("VehiclesDropOffKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.VehicleWebService.Customers DriverCustomer {
            get {
                return this.DriverCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverCustomerField, value) != true)) {
                    this.DriverCustomerField = value;
                    this.RaisePropertyChanged("DriverCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles RentedVehicle {
            get {
                return this.RentedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehicleField, value) != true)) {
                    this.RentedVehicleField = value;
                    this.RaisePropertyChanged("RentedVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.VehicleWebService.Companies SupplierCompany {
            get {
                return this.SupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCompanyField, value) != true)) {
                    this.SupplierCompanyField = value;
                    this.RaisePropertyChanged("SupplierCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CustomerPhoneNumber {
            get {
                return this.CustomerPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNumberField, value) != true)) {
                    this.CustomerPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SecondPhoneNumber {
            get {
                return this.SecondPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPhoneNumberField, value) != true)) {
                    this.SecondPhoneNumberField = value;
                    this.RaisePropertyChanged("SecondPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NationalIdcard {
            get {
                return this.NationalIdcardField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdcardField, value) != true)) {
                    this.NationalIdcardField = value;
                    this.RaisePropertyChanged("NationalIdcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Companies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAdressField;
        
        private int NumOfVehicleField;
        
        private System.Nullable<int> CompanyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] VehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Employees[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyEmail {
            get {
                return this.CompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailField, value) != true)) {
                    this.CompanyEmailField = value;
                    this.RaisePropertyChanged("CompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyCity {
            get {
                return this.CompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCityField, value) != true)) {
                    this.CompanyCityField = value;
                    this.RaisePropertyChanged("CompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CompanyAdress {
            get {
                return this.CompanyAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAdressField, value) != true)) {
                    this.CompanyAdressField = value;
                    this.RaisePropertyChanged("CompanyAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumOfVehicle {
            get {
                return this.NumOfVehicleField;
            }
            set {
                if ((this.NumOfVehicleField.Equals(value) != true)) {
                    this.NumOfVehicleField = value;
                    this.RaisePropertyChanged("NumOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> CompanyPoints {
            get {
                return this.CompanyPointsField;
            }
            set {
                if ((this.CompanyPointsField.Equals(value) != true)) {
                    this.CompanyPointsField = value;
                    this.RaisePropertyChanged("CompanyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.VehicleWebService.Employees[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeesIdField;
        
        private int EmployeesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployessPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.VehicleWebService.Companies EmployeesCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeesId {
            get {
                return this.EmployeesIdField;
            }
            set {
                if ((this.EmployeesIdField.Equals(value) != true)) {
                    this.EmployeesIdField = value;
                    this.RaisePropertyChanged("EmployeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeesCompanyId {
            get {
                return this.EmployeesCompanyIdField;
            }
            set {
                if ((this.EmployeesCompanyIdField.Equals(value) != true)) {
                    this.EmployeesCompanyIdField = value;
                    this.RaisePropertyChanged("EmployeesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeesEmail {
            get {
                return this.EmployeesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesEmailField, value) != true)) {
                    this.EmployeesEmailField = value;
                    this.RaisePropertyChanged("EmployeesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployessPassword {
            get {
                return this.EmployessPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployessPasswordField, value) != true)) {
                    this.EmployessPasswordField = value;
                    this.RaisePropertyChanged("EmployessPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeesPhoneNumber {
            get {
                return this.EmployeesPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesPhoneNumberField, value) != true)) {
                    this.EmployeesPhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeesPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeesAddress {
            get {
                return this.EmployeesAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesAddressField, value) != true)) {
                    this.EmployeesAddressField = value;
                    this.RaisePropertyChanged("EmployeesAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.VehicleWebService.Companies EmployeesCompany {
            get {
                return this.EmployeesCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesCompanyField, value) != true)) {
                    this.EmployeesCompanyField = value;
                    this.RaisePropertyChanged("EmployeesCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleWebService.VehiclesWebServiceSoap")]
    public interface VehiclesWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetAllAvaliableVehiclesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAvaliableVehicles", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse GetAllAvaliableVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAvaliableVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse> GetAllAvaliableVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCompanysAllVehiclesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllVehicles", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse GetCompanysAllVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse> GetCompanysAllVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCompanysAllRentedVehiclesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllRentedVehicles", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse GetCompanysAllRentedVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllRentedVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse> GetCompanysAllRentedVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetVehicleByIDResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVehicleByID", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse GetVehicleByID(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVehicleByID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse> GetVehicleByIDAsync(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddVehicle", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse AddVehicle(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddVehicle", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse> AddVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateVehicle", ReplyAction="*")]
        CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse UpdateVehicle(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateVehicle", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse> UpdateVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteVehicle", ReplyAction="*")]
        bool DeleteVehicle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteVehicle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteVehicleAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAvaliableVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAvaliableVehicles", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequestBody Body;
        
        public GetAllAvaliableVehiclesRequest() {
        }
        
        public GetAllAvaliableVehiclesRequest(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAvaliableVehiclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime currentdatetime;
        
        public GetAllAvaliableVehiclesRequestBody() {
        }
        
        public GetAllAvaliableVehiclesRequestBody(System.DateTime currentdatetime) {
            this.currentdatetime = currentdatetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAvaliableVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAvaliableVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponseBody Body;
        
        public GetAllAvaliableVehiclesResponse() {
        }
        
        public GetAllAvaliableVehiclesResponse(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAvaliableVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetAllAvaliableVehiclesResult;
        
        public GetAllAvaliableVehiclesResponseBody() {
        }
        
        public GetAllAvaliableVehiclesResponseBody(CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetAllAvaliableVehiclesResult) {
            this.GetAllAvaliableVehiclesResult = GetAllAvaliableVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllVehicles", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequestBody Body;
        
        public GetCompanysAllVehiclesRequest() {
        }
        
        public GetCompanysAllVehiclesRequest(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllVehiclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyid;
        
        public GetCompanysAllVehiclesRequestBody() {
        }
        
        public GetCompanysAllVehiclesRequestBody(int companyid) {
            this.companyid = companyid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponseBody Body;
        
        public GetCompanysAllVehiclesResponse() {
        }
        
        public GetCompanysAllVehiclesResponse(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetCompanysAllVehiclesResult;
        
        public GetCompanysAllVehiclesResponseBody() {
        }
        
        public GetCompanysAllVehiclesResponseBody(CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetCompanysAllVehiclesResult) {
            this.GetCompanysAllVehiclesResult = GetCompanysAllVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllRentedVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllRentedVehicles", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequestBody Body;
        
        public GetCompanysAllRentedVehiclesRequest() {
        }
        
        public GetCompanysAllRentedVehiclesRequest(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllRentedVehiclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyid;
        
        public GetCompanysAllRentedVehiclesRequestBody() {
        }
        
        public GetCompanysAllRentedVehiclesRequestBody(int companyid) {
            this.companyid = companyid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllRentedVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllRentedVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponseBody Body;
        
        public GetCompanysAllRentedVehiclesResponse() {
        }
        
        public GetCompanysAllRentedVehiclesResponse(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllRentedVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] GetCompanysAllRentedVehiclesResult;
        
        public GetCompanysAllRentedVehiclesResponseBody() {
        }
        
        public GetCompanysAllRentedVehiclesResponseBody(CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] GetCompanysAllRentedVehiclesResult) {
            this.GetCompanysAllRentedVehiclesResult = GetCompanysAllRentedVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehicleByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehicleByID", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequestBody Body;
        
        public GetVehicleByIDRequest() {
        }
        
        public GetVehicleByIDRequest(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVehicleByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetVehicleByIDRequestBody() {
        }
        
        public GetVehicleByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehicleByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehicleByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponseBody Body;
        
        public GetVehicleByIDResponse() {
        }
        
        public GetVehicleByIDResponse(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVehicleByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles GetVehicleByIDResult;
        
        public GetVehicleByIDResponseBody() {
        }
        
        public GetVehicleByIDResponseBody(CarRentalManagementSystem.Web.VehicleWebService.Vehicles GetVehicleByIDResult) {
            this.GetVehicleByIDResult = GetVehicleByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddVehicle", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequestBody Body;
        
        public AddVehicleRequest() {
        }
        
        public AddVehicleRequest(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddVehicleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity;
        
        public AddVehicleRequestBody() {
        }
        
        public AddVehicleRequestBody(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddVehicleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponseBody Body;
        
        public AddVehicleResponse() {
        }
        
        public AddVehicleResponse(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddVehicleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddVehicleResult;
        
        public AddVehicleResponseBody() {
        }
        
        public AddVehicleResponseBody(bool AddVehicleResult) {
            this.AddVehicleResult = AddVehicleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateVehicle", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequestBody Body;
        
        public UpdateVehicleRequest() {
        }
        
        public UpdateVehicleRequest(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateVehicleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity;
        
        public UpdateVehicleRequestBody() {
        }
        
        public UpdateVehicleRequestBody(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateVehicleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponseBody Body;
        
        public UpdateVehicleResponse() {
        }
        
        public UpdateVehicleResponse(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateVehicleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateVehicleResult;
        
        public UpdateVehicleResponseBody() {
        }
        
        public UpdateVehicleResponseBody(bool UpdateVehicleResult) {
            this.UpdateVehicleResult = UpdateVehicleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehiclesWebServiceSoapChannel : CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiclesWebServiceSoapClient : System.ServiceModel.ClientBase<CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap>, CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap {
        
        public VehiclesWebServiceSoapClient() {
        }
        
        public VehiclesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiclesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiclesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiclesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetAllAvaliableVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest request) {
            return base.Channel.GetAllAvaliableVehicles(request);
        }
        
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetAllAvaliableVehicles(System.DateTime currentdatetime) {
            CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequestBody();
            inValue.Body.currentdatetime = currentdatetime;
            CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetAllAvaliableVehicles(inValue);
            return retVal.Body.GetAllAvaliableVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetAllAvaliableVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest request) {
            return base.Channel.GetAllAvaliableVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesResponse> GetAllAvaliableVehiclesAsync(System.DateTime currentdatetime) {
            CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetAllAvaliableVehiclesRequestBody();
            inValue.Body.currentdatetime = currentdatetime;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetAllAvaliableVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetCompanysAllVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest request) {
            return base.Channel.GetCompanysAllVehicles(request);
        }
        
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles[] GetCompanysAllVehicles(int companyid) {
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetCompanysAllVehicles(inValue);
            return retVal.Body.GetCompanysAllVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetCompanysAllVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest request) {
            return base.Channel.GetCompanysAllVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesResponse> GetCompanysAllVehiclesAsync(int companyid) {
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetCompanysAllVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetCompanysAllRentedVehicles(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest request) {
            return base.Channel.GetCompanysAllRentedVehicles(request);
        }
        
        public CarRentalManagementSystem.Web.VehicleWebService.RentedVehicles[] GetCompanysAllRentedVehicles(int companyid) {
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetCompanysAllRentedVehicles(inValue);
            return retVal.Body.GetCompanysAllRentedVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetCompanysAllRentedVehiclesAsync(CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest request) {
            return base.Channel.GetCompanysAllRentedVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesResponse> GetCompanysAllRentedVehiclesAsync(int companyid) {
            CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetCompanysAllRentedVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetCompanysAllRentedVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetVehicleByID(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest request) {
            return base.Channel.GetVehicleByID(request);
        }
        
        public CarRentalManagementSystem.Web.VehicleWebService.Vehicles GetVehicleByID(int id) {
            CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequestBody();
            inValue.Body.id = id;
            CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetVehicleByID(inValue);
            return retVal.Body.GetVehicleByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.GetVehicleByIDAsync(CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest request) {
            return base.Channel.GetVehicleByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDResponse> GetVehicleByIDAsync(int id) {
            CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.GetVehicleByIDRequestBody();
            inValue.Body.id = id;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).GetVehicleByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.AddVehicle(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest request) {
            return base.Channel.AddVehicle(request);
        }
        
        public bool AddVehicle(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).AddVehicle(inValue);
            return retVal.Body.AddVehicleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.AddVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest request) {
            return base.Channel.AddVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.AddVehicleResponse> AddVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.AddVehicleRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).AddVehicleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.UpdateVehicle(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest request) {
            return base.Channel.UpdateVehicle(request);
        }
        
        public bool UpdateVehicle(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse retVal = ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).UpdateVehicle(inValue);
            return retVal.Body.UpdateVehicleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse> CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap.UpdateVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest request) {
            return base.Channel.UpdateVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleResponse> UpdateVehicleAsync(CarRentalManagementSystem.Web.VehicleWebService.Vehicles entity) {
            CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest inValue = new CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.VehicleWebService.UpdateVehicleRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.VehicleWebService.VehiclesWebServiceSoap)(this)).UpdateVehicleAsync(inValue);
        }
        
        public bool DeleteVehicle(int id) {
            return base.Channel.DeleteVehicle(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteVehicleAsync(int id) {
            return base.Channel.DeleteVehicleAsync(id);
        }
    }
}
