//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManagementSystem.Web.RentedVehicleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedVehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentedVehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentIdField;
        
        private int RentedVehicleIdField;
        
        private int SupplierCompanyIdField;
        
        private int DriverCustomerIdField;
        
        private System.DateTime PickUpDateField;
        
        private System.DateTime DropOffDateField;
        
        private int VehiclesPickUpKmField;
        
        private int VehiclesDropOffKmField;
        
        private decimal RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Customers DriverCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Vehicles RentedVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Companies SupplierCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentId {
            get {
                return this.RentIdField;
            }
            set {
                if ((this.RentIdField.Equals(value) != true)) {
                    this.RentIdField = value;
                    this.RaisePropertyChanged("RentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentedVehicleId {
            get {
                return this.RentedVehicleIdField;
            }
            set {
                if ((this.RentedVehicleIdField.Equals(value) != true)) {
                    this.RentedVehicleIdField = value;
                    this.RaisePropertyChanged("RentedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierCompanyId {
            get {
                return this.SupplierCompanyIdField;
            }
            set {
                if ((this.SupplierCompanyIdField.Equals(value) != true)) {
                    this.SupplierCompanyIdField = value;
                    this.RaisePropertyChanged("SupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DriverCustomerId {
            get {
                return this.DriverCustomerIdField;
            }
            set {
                if ((this.DriverCustomerIdField.Equals(value) != true)) {
                    this.DriverCustomerIdField = value;
                    this.RaisePropertyChanged("DriverCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DropOffDate {
            get {
                return this.DropOffDateField;
            }
            set {
                if ((this.DropOffDateField.Equals(value) != true)) {
                    this.DropOffDateField = value;
                    this.RaisePropertyChanged("DropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehiclesPickUpKm {
            get {
                return this.VehiclesPickUpKmField;
            }
            set {
                if ((this.VehiclesPickUpKmField.Equals(value) != true)) {
                    this.VehiclesPickUpKmField = value;
                    this.RaisePropertyChanged("VehiclesPickUpKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int VehiclesDropOffKm {
            get {
                return this.VehiclesDropOffKmField;
            }
            set {
                if ((this.VehiclesDropOffKmField.Equals(value) != true)) {
                    this.VehiclesDropOffKmField = value;
                    this.RaisePropertyChanged("VehiclesDropOffKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Customers DriverCustomer {
            get {
                return this.DriverCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverCustomerField, value) != true)) {
                    this.DriverCustomerField = value;
                    this.RaisePropertyChanged("DriverCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Vehicles RentedVehicle {
            get {
                return this.RentedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehicleField, value) != true)) {
                    this.RentedVehicleField = value;
                    this.RaisePropertyChanged("RentedVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Companies SupplierCompany {
            get {
                return this.SupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCompanyField, value) != true)) {
                    this.SupplierCompanyField = value;
                    this.RaisePropertyChanged("SupplierCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CustomerPhoneNumber {
            get {
                return this.CustomerPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNumberField, value) != true)) {
                    this.CustomerPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SecondPhoneNumber {
            get {
                return this.SecondPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPhoneNumberField, value) != true)) {
                    this.SecondPhoneNumberField = value;
                    this.RaisePropertyChanged("SecondPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NationalIdcard {
            get {
                return this.NationalIdcardField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdcardField, value) != true)) {
                    this.NationalIdcardField = value;
                    this.RaisePropertyChanged("NationalIdcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        private int VehiclesInstantKmField;
        
        private bool HasAirbagField;
        
        private int TrunkVolumeField;
        
        private int SeatingCapacityField;
        
        private decimal DailyRentalPriceField;
        
        private int AgeLimitForDrivingThisCarField;
        
        private int KmLimitPerDayField;
        
        private int RequiredDrivingLicenseAgeField;
        
        private System.DateTime IsAvailableAtTimeField;
        
        private int VehiclesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int VehiclesInstantKm {
            get {
                return this.VehiclesInstantKmField;
            }
            set {
                if ((this.VehiclesInstantKmField.Equals(value) != true)) {
                    this.VehiclesInstantKmField = value;
                    this.RaisePropertyChanged("VehiclesInstantKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TrunkVolume {
            get {
                return this.TrunkVolumeField;
            }
            set {
                if ((this.TrunkVolumeField.Equals(value) != true)) {
                    this.TrunkVolumeField = value;
                    this.RaisePropertyChanged("TrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AgeLimitForDrivingThisCar {
            get {
                return this.AgeLimitForDrivingThisCarField;
            }
            set {
                if ((this.AgeLimitForDrivingThisCarField.Equals(value) != true)) {
                    this.AgeLimitForDrivingThisCarField = value;
                    this.RaisePropertyChanged("AgeLimitForDrivingThisCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int KmLimitPerDay {
            get {
                return this.KmLimitPerDayField;
            }
            set {
                if ((this.KmLimitPerDayField.Equals(value) != true)) {
                    this.KmLimitPerDayField = value;
                    this.RaisePropertyChanged("KmLimitPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int RequiredDrivingLicenseAge {
            get {
                return this.RequiredDrivingLicenseAgeField;
            }
            set {
                if ((this.RequiredDrivingLicenseAgeField.Equals(value) != true)) {
                    this.RequiredDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("RequiredDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime IsAvailableAtTime {
            get {
                return this.IsAvailableAtTimeField;
            }
            set {
                if ((this.IsAvailableAtTimeField.Equals(value) != true)) {
                    this.IsAvailableAtTimeField = value;
                    this.RaisePropertyChanged("IsAvailableAtTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int VehiclesCompanyId {
            get {
                return this.VehiclesCompanyIdField;
            }
            set {
                if ((this.VehiclesCompanyIdField.Equals(value) != true)) {
                    this.VehiclesCompanyIdField = value;
                    this.RaisePropertyChanged("VehiclesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Companies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAdressField;
        
        private int NumOfVehicleField;
        
        private System.Nullable<int> CompanyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Vehicles[] VehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Employees[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyEmail {
            get {
                return this.CompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailField, value) != true)) {
                    this.CompanyEmailField = value;
                    this.RaisePropertyChanged("CompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyCity {
            get {
                return this.CompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCityField, value) != true)) {
                    this.CompanyCityField = value;
                    this.RaisePropertyChanged("CompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CompanyAdress {
            get {
                return this.CompanyAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAdressField, value) != true)) {
                    this.CompanyAdressField = value;
                    this.RaisePropertyChanged("CompanyAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumOfVehicle {
            get {
                return this.NumOfVehicleField;
            }
            set {
                if ((this.NumOfVehicleField.Equals(value) != true)) {
                    this.NumOfVehicleField = value;
                    this.RaisePropertyChanged("NumOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> CompanyPoints {
            get {
                return this.CompanyPointsField;
            }
            set {
                if ((this.CompanyPointsField.Equals(value) != true)) {
                    this.CompanyPointsField = value;
                    this.RaisePropertyChanged("CompanyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Vehicles[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Employees[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalRequests", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentalRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentalRequestIdField;
        
        private int RentalRequestCustomerIdField;
        
        private int RequestedSupplierCompanyIdField;
        
        private int RequestedVehicleIdField;
        
        private System.DateTime RequestedPickUpDateField;
        
        private System.DateTime RequestedDropOffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Customers RentalRequestCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Companies RequestedSupplierCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Vehicles RequestedVehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentalRequestId {
            get {
                return this.RentalRequestIdField;
            }
            set {
                if ((this.RentalRequestIdField.Equals(value) != true)) {
                    this.RentalRequestIdField = value;
                    this.RaisePropertyChanged("RentalRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RentalRequestCustomerId {
            get {
                return this.RentalRequestCustomerIdField;
            }
            set {
                if ((this.RentalRequestCustomerIdField.Equals(value) != true)) {
                    this.RentalRequestCustomerIdField = value;
                    this.RaisePropertyChanged("RentalRequestCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestedSupplierCompanyId {
            get {
                return this.RequestedSupplierCompanyIdField;
            }
            set {
                if ((this.RequestedSupplierCompanyIdField.Equals(value) != true)) {
                    this.RequestedSupplierCompanyIdField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestedVehicleId {
            get {
                return this.RequestedVehicleIdField;
            }
            set {
                if ((this.RequestedVehicleIdField.Equals(value) != true)) {
                    this.RequestedVehicleIdField = value;
                    this.RaisePropertyChanged("RequestedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime RequestedPickUpDate {
            get {
                return this.RequestedPickUpDateField;
            }
            set {
                if ((this.RequestedPickUpDateField.Equals(value) != true)) {
                    this.RequestedPickUpDateField = value;
                    this.RaisePropertyChanged("RequestedPickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime RequestedDropOffDate {
            get {
                return this.RequestedDropOffDateField;
            }
            set {
                if ((this.RequestedDropOffDateField.Equals(value) != true)) {
                    this.RequestedDropOffDateField = value;
                    this.RaisePropertyChanged("RequestedDropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Customers RentalRequestCustomer {
            get {
                return this.RentalRequestCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestCustomerField, value) != true)) {
                    this.RentalRequestCustomerField = value;
                    this.RaisePropertyChanged("RentalRequestCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Companies RequestedSupplierCompany {
            get {
                return this.RequestedSupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedSupplierCompanyField, value) != true)) {
                    this.RequestedSupplierCompanyField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Vehicles RequestedVehicle {
            get {
                return this.RequestedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedVehicleField, value) != true)) {
                    this.RequestedVehicleField = value;
                    this.RaisePropertyChanged("RequestedVehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeesIdField;
        
        private int EmployeesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployessPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.RentedVehicleService.Companies EmployeesCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeesId {
            get {
                return this.EmployeesIdField;
            }
            set {
                if ((this.EmployeesIdField.Equals(value) != true)) {
                    this.EmployeesIdField = value;
                    this.RaisePropertyChanged("EmployeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeesCompanyId {
            get {
                return this.EmployeesCompanyIdField;
            }
            set {
                if ((this.EmployeesCompanyIdField.Equals(value) != true)) {
                    this.EmployeesCompanyIdField = value;
                    this.RaisePropertyChanged("EmployeesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeesEmail {
            get {
                return this.EmployeesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesEmailField, value) != true)) {
                    this.EmployeesEmailField = value;
                    this.RaisePropertyChanged("EmployeesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployessPassword {
            get {
                return this.EmployessPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployessPasswordField, value) != true)) {
                    this.EmployessPasswordField = value;
                    this.RaisePropertyChanged("EmployessPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeesPhoneNumber {
            get {
                return this.EmployeesPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesPhoneNumberField, value) != true)) {
                    this.EmployeesPhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeesPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeesAddress {
            get {
                return this.EmployeesAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesAddressField, value) != true)) {
                    this.EmployeesAddressField = value;
                    this.RaisePropertyChanged("EmployeesAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.RentedVehicleService.Companies EmployeesCompany {
            get {
                return this.EmployeesCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesCompanyField, value) != true)) {
                    this.EmployeesCompanyField = value;
                    this.RaisePropertyChanged("EmployeesCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentedVehicleService.RentedVehiclesWebServiceSoap")]
    public interface RentedVehiclesWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentVehicle", ReplyAction="*")]
        CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse RentVehicle(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentVehicle", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse> RentVehicleAsync(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCompanysRentedVehiclesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysRentedVehicles", ReplyAction="*")]
        CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse GetCompanysRentedVehicles(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysRentedVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse> GetCompanysRentedVehiclesAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCustomersRentedVehiclesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomersRentedVehicles", ReplyAction="*")]
        CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse GetCustomersRentedVehicles(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomersRentedVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse> GetCustomersRentedVehiclesAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetRentedVehicleByIdResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentedVehicleById", ReplyAction="*")]
        CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse GetRentedVehicleById(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentedVehicleById", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse> GetRentedVehicleByIdAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentVehicle", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequestBody Body;
        
        public RentVehicleRequest() {
        }
        
        public RentVehicleRequest(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentVehicleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles entity;
        
        public RentVehicleRequestBody() {
        }
        
        public RentVehicleRequestBody(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentVehicleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponseBody Body;
        
        public RentVehicleResponse() {
        }
        
        public RentVehicleResponse(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentVehicleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RentVehicleResult;
        
        public RentVehicleResponseBody() {
        }
        
        public RentVehicleResponseBody(bool RentVehicleResult) {
            this.RentVehicleResult = RentVehicleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysRentedVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysRentedVehicles", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequestBody Body;
        
        public GetCompanysRentedVehiclesRequest() {
        }
        
        public GetCompanysRentedVehiclesRequest(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysRentedVehiclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyid;
        
        public GetCompanysRentedVehiclesRequestBody() {
        }
        
        public GetCompanysRentedVehiclesRequestBody(int companyid) {
            this.companyid = companyid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysRentedVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysRentedVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponseBody Body;
        
        public GetCompanysRentedVehiclesResponse() {
        }
        
        public GetCompanysRentedVehiclesResponse(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysRentedVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCompanysRentedVehiclesResult;
        
        public GetCompanysRentedVehiclesResponseBody() {
        }
        
        public GetCompanysRentedVehiclesResponseBody(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCompanysRentedVehiclesResult) {
            this.GetCompanysRentedVehiclesResult = GetCompanysRentedVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRentedVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersRentedVehicles", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequestBody Body;
        
        public GetCustomersRentedVehiclesRequest() {
        }
        
        public GetCustomersRentedVehiclesRequest(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersRentedVehiclesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerid;
        
        public GetCustomersRentedVehiclesRequestBody() {
        }
        
        public GetCustomersRentedVehiclesRequestBody(int customerid) {
            this.customerid = customerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRentedVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersRentedVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponseBody Body;
        
        public GetCustomersRentedVehiclesResponse() {
        }
        
        public GetCustomersRentedVehiclesResponse(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersRentedVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCustomersRentedVehiclesResult;
        
        public GetCustomersRentedVehiclesResponseBody() {
        }
        
        public GetCustomersRentedVehiclesResponseBody(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCustomersRentedVehiclesResult) {
            this.GetCustomersRentedVehiclesResult = GetCustomersRentedVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRentedVehicleByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRentedVehicleById", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequestBody Body;
        
        public GetRentedVehicleByIdRequest() {
        }
        
        public GetRentedVehicleByIdRequest(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRentedVehicleByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRentedVehicleByIdRequestBody() {
        }
        
        public GetRentedVehicleByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRentedVehicleByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRentedVehicleByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponseBody Body;
        
        public GetRentedVehicleByIdResponse() {
        }
        
        public GetRentedVehicleByIdResponse(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRentedVehicleByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles GetRentedVehicleByIdResult;
        
        public GetRentedVehicleByIdResponseBody() {
        }
        
        public GetRentedVehicleByIdResponseBody(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles GetRentedVehicleByIdResult) {
            this.GetRentedVehicleByIdResult = GetRentedVehicleByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RentedVehiclesWebServiceSoapChannel : CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentedVehiclesWebServiceSoapClient : System.ServiceModel.ClientBase<CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap>, CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap {
        
        public RentedVehiclesWebServiceSoapClient() {
        }
        
        public RentedVehiclesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentedVehiclesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentedVehiclesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentedVehiclesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.RentVehicle(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest request) {
            return base.Channel.RentVehicle(request);
        }
        
        public bool RentVehicle(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles entity) {
            CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse retVal = ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).RentVehicle(inValue);
            return retVal.Body.RentVehicleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse> CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.RentVehicleAsync(CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest request) {
            return base.Channel.RentVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleResponse> RentVehicleAsync(CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles entity) {
            CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.RentVehicleRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).RentVehicleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetCompanysRentedVehicles(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest request) {
            return base.Channel.GetCompanysRentedVehicles(request);
        }
        
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCompanysRentedVehicles(int companyid) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse retVal = ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetCompanysRentedVehicles(inValue);
            return retVal.Body.GetCompanysRentedVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse> CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetCompanysRentedVehiclesAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest request) {
            return base.Channel.GetCompanysRentedVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesResponse> GetCompanysRentedVehiclesAsync(int companyid) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetCompanysRentedVehiclesRequestBody();
            inValue.Body.companyid = companyid;
            return ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetCompanysRentedVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetCustomersRentedVehicles(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest request) {
            return base.Channel.GetCustomersRentedVehicles(request);
        }
        
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles[] GetCustomersRentedVehicles(int customerid) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequestBody();
            inValue.Body.customerid = customerid;
            CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse retVal = ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetCustomersRentedVehicles(inValue);
            return retVal.Body.GetCustomersRentedVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse> CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetCustomersRentedVehiclesAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest request) {
            return base.Channel.GetCustomersRentedVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesResponse> GetCustomersRentedVehiclesAsync(int customerid) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetCustomersRentedVehiclesRequestBody();
            inValue.Body.customerid = customerid;
            return ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetCustomersRentedVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetRentedVehicleById(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest request) {
            return base.Channel.GetRentedVehicleById(request);
        }
        
        public CarRentalManagementSystem.Web.RentedVehicleService.RentedVehicles GetRentedVehicleById(int id) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequestBody();
            inValue.Body.id = id;
            CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse retVal = ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetRentedVehicleById(inValue);
            return retVal.Body.GetRentedVehicleByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse> CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap.GetRentedVehicleByIdAsync(CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest request) {
            return base.Channel.GetRentedVehicleByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdResponse> GetRentedVehicleByIdAsync(int id) {
            CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest inValue = new CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequest();
            inValue.Body = new CarRentalManagementSystem.Web.RentedVehicleService.GetRentedVehicleByIdRequestBody();
            inValue.Body.id = id;
            return ((CarRentalManagementSystem.Web.RentedVehicleService.RentedVehiclesWebServiceSoap)(this)).GetRentedVehicleByIdAsync(inValue);
        }
    }
}
