//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManagementSystem.Web.CustomerWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CustomerPhoneNumber {
            get {
                return this.CustomerPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNumberField, value) != true)) {
                    this.CustomerPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SecondPhoneNumber {
            get {
                return this.SecondPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPhoneNumberField, value) != true)) {
                    this.SecondPhoneNumberField = value;
                    this.RaisePropertyChanged("SecondPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NationalIdcard {
            get {
                return this.NationalIdcardField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdcardField, value) != true)) {
                    this.NationalIdcardField = value;
                    this.RaisePropertyChanged("NationalIdcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalRequests", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentalRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentalRequestIdField;
        
        private int RentalRequestCustomerIdField;
        
        private int RequestedSupplierCompanyIdField;
        
        private int RequestedVehicleIdField;
        
        private System.DateTime RequestedPickUpDateField;
        
        private System.DateTime RequestedDropOffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Customers RentalRequestCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Companies RequestedSupplierCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Vehicles RequestedVehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentalRequestId {
            get {
                return this.RentalRequestIdField;
            }
            set {
                if ((this.RentalRequestIdField.Equals(value) != true)) {
                    this.RentalRequestIdField = value;
                    this.RaisePropertyChanged("RentalRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RentalRequestCustomerId {
            get {
                return this.RentalRequestCustomerIdField;
            }
            set {
                if ((this.RentalRequestCustomerIdField.Equals(value) != true)) {
                    this.RentalRequestCustomerIdField = value;
                    this.RaisePropertyChanged("RentalRequestCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestedSupplierCompanyId {
            get {
                return this.RequestedSupplierCompanyIdField;
            }
            set {
                if ((this.RequestedSupplierCompanyIdField.Equals(value) != true)) {
                    this.RequestedSupplierCompanyIdField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestedVehicleId {
            get {
                return this.RequestedVehicleIdField;
            }
            set {
                if ((this.RequestedVehicleIdField.Equals(value) != true)) {
                    this.RequestedVehicleIdField = value;
                    this.RaisePropertyChanged("RequestedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime RequestedPickUpDate {
            get {
                return this.RequestedPickUpDateField;
            }
            set {
                if ((this.RequestedPickUpDateField.Equals(value) != true)) {
                    this.RequestedPickUpDateField = value;
                    this.RaisePropertyChanged("RequestedPickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime RequestedDropOffDate {
            get {
                return this.RequestedDropOffDateField;
            }
            set {
                if ((this.RequestedDropOffDateField.Equals(value) != true)) {
                    this.RequestedDropOffDateField = value;
                    this.RaisePropertyChanged("RequestedDropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers RentalRequestCustomer {
            get {
                return this.RentalRequestCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestCustomerField, value) != true)) {
                    this.RentalRequestCustomerField = value;
                    this.RaisePropertyChanged("RentalRequestCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRentalManagementSystem.Web.CustomerWebService.Companies RequestedSupplierCompany {
            get {
                return this.RequestedSupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedSupplierCompanyField, value) != true)) {
                    this.RequestedSupplierCompanyField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.CustomerWebService.Vehicles RequestedVehicle {
            get {
                return this.RequestedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedVehicleField, value) != true)) {
                    this.RequestedVehicleField = value;
                    this.RaisePropertyChanged("RequestedVehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedVehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentedVehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentIdField;
        
        private int RentedVehicleIdField;
        
        private int SupplierCompanyIdField;
        
        private int DriverCustomerIdField;
        
        private System.DateTime PickUpDateField;
        
        private System.DateTime DropOffDateField;
        
        private int VehiclesPickUpKmField;
        
        private int VehiclesDropOffKmField;
        
        private decimal RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Customers DriverCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Vehicles RentedVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Companies SupplierCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentId {
            get {
                return this.RentIdField;
            }
            set {
                if ((this.RentIdField.Equals(value) != true)) {
                    this.RentIdField = value;
                    this.RaisePropertyChanged("RentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentedVehicleId {
            get {
                return this.RentedVehicleIdField;
            }
            set {
                if ((this.RentedVehicleIdField.Equals(value) != true)) {
                    this.RentedVehicleIdField = value;
                    this.RaisePropertyChanged("RentedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierCompanyId {
            get {
                return this.SupplierCompanyIdField;
            }
            set {
                if ((this.SupplierCompanyIdField.Equals(value) != true)) {
                    this.SupplierCompanyIdField = value;
                    this.RaisePropertyChanged("SupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DriverCustomerId {
            get {
                return this.DriverCustomerIdField;
            }
            set {
                if ((this.DriverCustomerIdField.Equals(value) != true)) {
                    this.DriverCustomerIdField = value;
                    this.RaisePropertyChanged("DriverCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DropOffDate {
            get {
                return this.DropOffDateField;
            }
            set {
                if ((this.DropOffDateField.Equals(value) != true)) {
                    this.DropOffDateField = value;
                    this.RaisePropertyChanged("DropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehiclesPickUpKm {
            get {
                return this.VehiclesPickUpKmField;
            }
            set {
                if ((this.VehiclesPickUpKmField.Equals(value) != true)) {
                    this.VehiclesPickUpKmField = value;
                    this.RaisePropertyChanged("VehiclesPickUpKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int VehiclesDropOffKm {
            get {
                return this.VehiclesDropOffKmField;
            }
            set {
                if ((this.VehiclesDropOffKmField.Equals(value) != true)) {
                    this.VehiclesDropOffKmField = value;
                    this.RaisePropertyChanged("VehiclesDropOffKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers DriverCustomer {
            get {
                return this.DriverCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverCustomerField, value) != true)) {
                    this.DriverCustomerField = value;
                    this.RaisePropertyChanged("DriverCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.CustomerWebService.Vehicles RentedVehicle {
            get {
                return this.RentedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehicleField, value) != true)) {
                    this.RentedVehicleField = value;
                    this.RaisePropertyChanged("RentedVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.CustomerWebService.Companies SupplierCompany {
            get {
                return this.SupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCompanyField, value) != true)) {
                    this.SupplierCompanyField = value;
                    this.RaisePropertyChanged("SupplierCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Companies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAdressField;
        
        private int NumOfVehicleField;
        
        private System.Nullable<int> CompanyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Vehicles[] VehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Employees[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyEmail {
            get {
                return this.CompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailField, value) != true)) {
                    this.CompanyEmailField = value;
                    this.RaisePropertyChanged("CompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyCity {
            get {
                return this.CompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCityField, value) != true)) {
                    this.CompanyCityField = value;
                    this.RaisePropertyChanged("CompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CompanyAdress {
            get {
                return this.CompanyAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAdressField, value) != true)) {
                    this.CompanyAdressField = value;
                    this.RaisePropertyChanged("CompanyAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumOfVehicle {
            get {
                return this.NumOfVehicleField;
            }
            set {
                if ((this.NumOfVehicleField.Equals(value) != true)) {
                    this.NumOfVehicleField = value;
                    this.RaisePropertyChanged("NumOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> CompanyPoints {
            get {
                return this.CompanyPointsField;
            }
            set {
                if ((this.CompanyPointsField.Equals(value) != true)) {
                    this.CompanyPointsField = value;
                    this.RaisePropertyChanged("CompanyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.CustomerWebService.Vehicles[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.CustomerWebService.Employees[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        private int VehiclesInstantKmField;
        
        private bool HasAirbagField;
        
        private int TrunkVolumeField;
        
        private int SeatingCapacityField;
        
        private decimal DailyRentalPriceField;
        
        private int AgeLimitForDrivingThisCarField;
        
        private int KmLimitPerDayField;
        
        private int RequiredDrivingLicenseAgeField;
        
        private System.DateTime IsAvailableAtTimeField;
        
        private int VehiclesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int VehiclesInstantKm {
            get {
                return this.VehiclesInstantKmField;
            }
            set {
                if ((this.VehiclesInstantKmField.Equals(value) != true)) {
                    this.VehiclesInstantKmField = value;
                    this.RaisePropertyChanged("VehiclesInstantKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TrunkVolume {
            get {
                return this.TrunkVolumeField;
            }
            set {
                if ((this.TrunkVolumeField.Equals(value) != true)) {
                    this.TrunkVolumeField = value;
                    this.RaisePropertyChanged("TrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AgeLimitForDrivingThisCar {
            get {
                return this.AgeLimitForDrivingThisCarField;
            }
            set {
                if ((this.AgeLimitForDrivingThisCarField.Equals(value) != true)) {
                    this.AgeLimitForDrivingThisCarField = value;
                    this.RaisePropertyChanged("AgeLimitForDrivingThisCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int KmLimitPerDay {
            get {
                return this.KmLimitPerDayField;
            }
            set {
                if ((this.KmLimitPerDayField.Equals(value) != true)) {
                    this.KmLimitPerDayField = value;
                    this.RaisePropertyChanged("KmLimitPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int RequiredDrivingLicenseAge {
            get {
                return this.RequiredDrivingLicenseAgeField;
            }
            set {
                if ((this.RequiredDrivingLicenseAgeField.Equals(value) != true)) {
                    this.RequiredDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("RequiredDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime IsAvailableAtTime {
            get {
                return this.IsAvailableAtTimeField;
            }
            set {
                if ((this.IsAvailableAtTimeField.Equals(value) != true)) {
                    this.IsAvailableAtTimeField = value;
                    this.RaisePropertyChanged("IsAvailableAtTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int VehiclesCompanyId {
            get {
                return this.VehiclesCompanyIdField;
            }
            set {
                if ((this.VehiclesCompanyIdField.Equals(value) != true)) {
                    this.VehiclesCompanyIdField = value;
                    this.RaisePropertyChanged("VehiclesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public CarRentalManagementSystem.Web.CustomerWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeesIdField;
        
        private int EmployeesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployessPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.CustomerWebService.Companies EmployeesCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeesId {
            get {
                return this.EmployeesIdField;
            }
            set {
                if ((this.EmployeesIdField.Equals(value) != true)) {
                    this.EmployeesIdField = value;
                    this.RaisePropertyChanged("EmployeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeesCompanyId {
            get {
                return this.EmployeesCompanyIdField;
            }
            set {
                if ((this.EmployeesCompanyIdField.Equals(value) != true)) {
                    this.EmployeesCompanyIdField = value;
                    this.RaisePropertyChanged("EmployeesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeesEmail {
            get {
                return this.EmployeesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesEmailField, value) != true)) {
                    this.EmployeesEmailField = value;
                    this.RaisePropertyChanged("EmployeesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployessPassword {
            get {
                return this.EmployessPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployessPasswordField, value) != true)) {
                    this.EmployessPasswordField = value;
                    this.RaisePropertyChanged("EmployessPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeesPhoneNumber {
            get {
                return this.EmployeesPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesPhoneNumberField, value) != true)) {
                    this.EmployeesPhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeesPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeesAddress {
            get {
                return this.EmployeesAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesAddressField, value) != true)) {
                    this.EmployeesAddressField = value;
                    this.RaisePropertyChanged("EmployeesAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.CustomerWebService.Companies EmployeesCompany {
            get {
                return this.EmployeesCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesCompanyField, value) != true)) {
                    this.EmployeesCompanyField = value;
                    this.RaisePropertyChanged("EmployeesCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerWebService.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsCustomer", ReplyAction="*")]
        CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse SignUpAsCustomer(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse> SignUpAsCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki email öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsCustomer", ReplyAction="*")]
        CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse LogInAsCustomer(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse> LogInAsCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomerAccount", ReplyAction="*")]
        bool DeleteCustomerAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomerAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAccountAsync(int id);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse UpdateAccount(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetAllCustomerResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomer", ReplyAction="*")]
        CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse GetAllCustomer(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse> GetAllCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCustomerInformationByIDResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInformationByID", ReplyAction="*")]
        CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse GetCustomerInformationByID(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInformationByID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse> GetCustomerInformationByIDAsync(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAsCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequestBody Body;
        
        public SignUpAsCustomerRequest() {
        }
        
        public SignUpAsCustomerRequest(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAsCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers entity;
        
        public SignUpAsCustomerRequestBody() {
        }
        
        public SignUpAsCustomerRequestBody(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAsCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponseBody Body;
        
        public SignUpAsCustomerResponse() {
        }
        
        public SignUpAsCustomerResponse(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAsCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignUpAsCustomerResult;
        
        public SignUpAsCustomerResponseBody() {
        }
        
        public SignUpAsCustomerResponseBody(bool SignUpAsCustomerResult) {
            this.SignUpAsCustomerResult = SignUpAsCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequestBody Body;
        
        public LogInAsCustomerRequest() {
        }
        
        public LogInAsCustomerRequest(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInAsCustomerRequestBody() {
        }
        
        public LogInAsCustomerRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponseBody Body;
        
        public LogInAsCustomerResponse() {
        }
        
        public LogInAsCustomerResponse(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInAsCustomerResult;
        
        public LogInAsCustomerResponseBody() {
        }
        
        public LogInAsCustomerResponseBody(bool LogInAsCustomerResult) {
            this.LogInAsCustomerResult = LogInAsCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccount", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequestBody Body;
        
        public UpdateAccountRequest() {
        }
        
        public UpdateAccountRequest(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers entity;
        
        public UpdateAccountRequestBody() {
        }
        
        public UpdateAccountRequestBody(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponseBody Body;
        
        public UpdateAccountResponse() {
        }
        
        public UpdateAccountResponse(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateAccountResult;
        
        public UpdateAccountResponseBody() {
        }
        
        public UpdateAccountResponseBody(bool UpdateAccountResult) {
            this.UpdateAccountResult = UpdateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequestBody Body;
        
        public GetAllCustomerRequest() {
        }
        
        public GetAllCustomerRequest(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCustomerRequestBody {
        
        public GetAllCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponseBody Body;
        
        public GetAllCustomerResponse() {
        }
        
        public GetAllCustomerResponse(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers[] GetAllCustomerResult;
        
        public GetAllCustomerResponseBody() {
        }
        
        public GetAllCustomerResponseBody(CarRentalManagementSystem.Web.CustomerWebService.Customers[] GetAllCustomerResult) {
            this.GetAllCustomerResult = GetAllCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInformationByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInformationByID", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequestBody Body;
        
        public GetCustomerInformationByIDRequest() {
        }
        
        public GetCustomerInformationByIDRequest(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInformationByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCustomerInformationByIDRequestBody() {
        }
        
        public GetCustomerInformationByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInformationByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInformationByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponseBody Body;
        
        public GetCustomerInformationByIDResponse() {
        }
        
        public GetCustomerInformationByIDResponse(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInformationByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.CustomerWebService.Customers GetCustomerInformationByIDResult;
        
        public GetCustomerInformationByIDResponseBody() {
        }
        
        public GetCustomerInformationByIDResponseBody(CarRentalManagementSystem.Web.CustomerWebService.Customers GetCustomerInformationByIDResult) {
            this.GetCustomerInformationByIDResult = GetCustomerInformationByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap>, CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.SignUpAsCustomer(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest request) {
            return base.Channel.SignUpAsCustomer(request);
        }
        
        public bool SignUpAsCustomer(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse retVal = ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).SignUpAsCustomer(inValue);
            return retVal.Body.SignUpAsCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse> CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.SignUpAsCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest request) {
            return base.Channel.SignUpAsCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerResponse> SignUpAsCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.SignUpAsCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).SignUpAsCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.LogInAsCustomer(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest request) {
            return base.Channel.LogInAsCustomer(request);
        }
        
        public bool LogInAsCustomer(string email, string password) {
            CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse retVal = ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).LogInAsCustomer(inValue);
            return retVal.Body.LogInAsCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse> CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.LogInAsCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest request) {
            return base.Channel.LogInAsCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerResponse> LogInAsCustomerAsync(string email, string password) {
            CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.LogInAsCustomerRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).LogInAsCustomerAsync(inValue);
        }
        
        public bool DeleteCustomerAccount(int id) {
            return base.Channel.DeleteCustomerAccount(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAccountAsync(int id) {
            return base.Channel.DeleteCustomerAccountAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.UpdateAccount(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public bool UpdateAccount(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse retVal = ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).UpdateAccount(inValue);
            return retVal.Body.UpdateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse> CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.UpdateAccountAsync(CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.CustomerWebService.Customers entity) {
            CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).UpdateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.GetAllCustomer(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest request) {
            return base.Channel.GetAllCustomer(request);
        }
        
        public CarRentalManagementSystem.Web.CustomerWebService.Customers[] GetAllCustomer() {
            CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequestBody();
            CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse retVal = ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).GetAllCustomer(inValue);
            return retVal.Body.GetAllCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse> CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.GetAllCustomerAsync(CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest request) {
            return base.Channel.GetAllCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerResponse> GetAllCustomerAsync() {
            CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.GetAllCustomerRequestBody();
            return ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).GetAllCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.GetCustomerInformationByID(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest request) {
            return base.Channel.GetCustomerInformationByID(request);
        }
        
        public CarRentalManagementSystem.Web.CustomerWebService.Customers GetCustomerInformationByID(int id) {
            CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequestBody();
            inValue.Body.id = id;
            CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse retVal = ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).GetCustomerInformationByID(inValue);
            return retVal.Body.GetCustomerInformationByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse> CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap.GetCustomerInformationByIDAsync(CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest request) {
            return base.Channel.GetCustomerInformationByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDResponse> GetCustomerInformationByIDAsync(int id) {
            CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest inValue = new CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.CustomerWebService.GetCustomerInformationByIDRequestBody();
            inValue.Body.id = id;
            return ((CarRentalManagementSystem.Web.CustomerWebService.CustomerWebServiceSoap)(this)).GetCustomerInformationByIDAsync(inValue);
        }
    }
}
