//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManagementSystem.Web.EmployeeWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeesIdField;
        
        private int EmployeesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployessPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeesAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Companies EmployeesCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeesId {
            get {
                return this.EmployeesIdField;
            }
            set {
                if ((this.EmployeesIdField.Equals(value) != true)) {
                    this.EmployeesIdField = value;
                    this.RaisePropertyChanged("EmployeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeesCompanyId {
            get {
                return this.EmployeesCompanyIdField;
            }
            set {
                if ((this.EmployeesCompanyIdField.Equals(value) != true)) {
                    this.EmployeesCompanyIdField = value;
                    this.RaisePropertyChanged("EmployeesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeesEmail {
            get {
                return this.EmployeesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesEmailField, value) != true)) {
                    this.EmployeesEmailField = value;
                    this.RaisePropertyChanged("EmployeesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployessPassword {
            get {
                return this.EmployessPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployessPasswordField, value) != true)) {
                    this.EmployessPasswordField = value;
                    this.RaisePropertyChanged("EmployessPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeesPhoneNumber {
            get {
                return this.EmployeesPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesPhoneNumberField, value) != true)) {
                    this.EmployeesPhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeesPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeesAddress {
            get {
                return this.EmployeesAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesAddressField, value) != true)) {
                    this.EmployeesAddressField = value;
                    this.RaisePropertyChanged("EmployeesAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Companies EmployeesCompany {
            get {
                return this.EmployeesCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesCompanyField, value) != true)) {
                    this.EmployeesCompanyField = value;
                    this.RaisePropertyChanged("EmployeesCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Companies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAdressField;
        
        private int NumOfVehicleField;
        
        private System.Nullable<int> CompanyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Vehicles[] VehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Employees[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyEmail {
            get {
                return this.CompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailField, value) != true)) {
                    this.CompanyEmailField = value;
                    this.RaisePropertyChanged("CompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyCity {
            get {
                return this.CompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCityField, value) != true)) {
                    this.CompanyCityField = value;
                    this.RaisePropertyChanged("CompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CompanyAdress {
            get {
                return this.CompanyAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAdressField, value) != true)) {
                    this.CompanyAdressField = value;
                    this.RaisePropertyChanged("CompanyAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumOfVehicle {
            get {
                return this.NumOfVehicleField;
            }
            set {
                if ((this.NumOfVehicleField.Equals(value) != true)) {
                    this.NumOfVehicleField = value;
                    this.RaisePropertyChanged("NumOfVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> CompanyPoints {
            get {
                return this.CompanyPointsField;
            }
            set {
                if ((this.CompanyPointsField.Equals(value) != true)) {
                    this.CompanyPointsField = value;
                    this.RaisePropertyChanged("CompanyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Vehicles[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        private int VehiclesInstantKmField;
        
        private bool HasAirbagField;
        
        private int TrunkVolumeField;
        
        private int SeatingCapacityField;
        
        private decimal DailyRentalPriceField;
        
        private int AgeLimitForDrivingThisCarField;
        
        private int KmLimitPerDayField;
        
        private int RequiredDrivingLicenseAgeField;
        
        private System.DateTime IsAvailableAtTimeField;
        
        private int VehiclesCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int VehiclesInstantKm {
            get {
                return this.VehiclesInstantKmField;
            }
            set {
                if ((this.VehiclesInstantKmField.Equals(value) != true)) {
                    this.VehiclesInstantKmField = value;
                    this.RaisePropertyChanged("VehiclesInstantKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TrunkVolume {
            get {
                return this.TrunkVolumeField;
            }
            set {
                if ((this.TrunkVolumeField.Equals(value) != true)) {
                    this.TrunkVolumeField = value;
                    this.RaisePropertyChanged("TrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int AgeLimitForDrivingThisCar {
            get {
                return this.AgeLimitForDrivingThisCarField;
            }
            set {
                if ((this.AgeLimitForDrivingThisCarField.Equals(value) != true)) {
                    this.AgeLimitForDrivingThisCarField = value;
                    this.RaisePropertyChanged("AgeLimitForDrivingThisCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int KmLimitPerDay {
            get {
                return this.KmLimitPerDayField;
            }
            set {
                if ((this.KmLimitPerDayField.Equals(value) != true)) {
                    this.KmLimitPerDayField = value;
                    this.RaisePropertyChanged("KmLimitPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int RequiredDrivingLicenseAge {
            get {
                return this.RequiredDrivingLicenseAgeField;
            }
            set {
                if ((this.RequiredDrivingLicenseAgeField.Equals(value) != true)) {
                    this.RequiredDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("RequiredDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime IsAvailableAtTime {
            get {
                return this.IsAvailableAtTimeField;
            }
            set {
                if ((this.IsAvailableAtTimeField.Equals(value) != true)) {
                    this.IsAvailableAtTimeField = value;
                    this.RaisePropertyChanged("IsAvailableAtTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int VehiclesCompanyId {
            get {
                return this.VehiclesCompanyIdField;
            }
            set {
                if ((this.VehiclesCompanyIdField.Equals(value) != true)) {
                    this.VehiclesCompanyIdField = value;
                    this.RaisePropertyChanged("VehiclesCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalRequests", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentalRequests : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentalRequestIdField;
        
        private int RentalRequestCustomerIdField;
        
        private int RequestedSupplierCompanyIdField;
        
        private int RequestedVehicleIdField;
        
        private System.DateTime RequestedPickUpDateField;
        
        private System.DateTime RequestedDropOffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Customers RentalRequestCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Companies RequestedSupplierCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Vehicles RequestedVehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentalRequestId {
            get {
                return this.RentalRequestIdField;
            }
            set {
                if ((this.RentalRequestIdField.Equals(value) != true)) {
                    this.RentalRequestIdField = value;
                    this.RaisePropertyChanged("RentalRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RentalRequestCustomerId {
            get {
                return this.RentalRequestCustomerIdField;
            }
            set {
                if ((this.RentalRequestCustomerIdField.Equals(value) != true)) {
                    this.RentalRequestCustomerIdField = value;
                    this.RaisePropertyChanged("RentalRequestCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestedSupplierCompanyId {
            get {
                return this.RequestedSupplierCompanyIdField;
            }
            set {
                if ((this.RequestedSupplierCompanyIdField.Equals(value) != true)) {
                    this.RequestedSupplierCompanyIdField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestedVehicleId {
            get {
                return this.RequestedVehicleIdField;
            }
            set {
                if ((this.RequestedVehicleIdField.Equals(value) != true)) {
                    this.RequestedVehicleIdField = value;
                    this.RaisePropertyChanged("RequestedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime RequestedPickUpDate {
            get {
                return this.RequestedPickUpDateField;
            }
            set {
                if ((this.RequestedPickUpDateField.Equals(value) != true)) {
                    this.RequestedPickUpDateField = value;
                    this.RaisePropertyChanged("RequestedPickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime RequestedDropOffDate {
            get {
                return this.RequestedDropOffDateField;
            }
            set {
                if ((this.RequestedDropOffDateField.Equals(value) != true)) {
                    this.RequestedDropOffDateField = value;
                    this.RaisePropertyChanged("RequestedDropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Customers RentalRequestCustomer {
            get {
                return this.RentalRequestCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestCustomerField, value) != true)) {
                    this.RentalRequestCustomerField = value;
                    this.RaisePropertyChanged("RentalRequestCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Companies RequestedSupplierCompany {
            get {
                return this.RequestedSupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedSupplierCompanyField, value) != true)) {
                    this.RequestedSupplierCompanyField = value;
                    this.RaisePropertyChanged("RequestedSupplierCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Vehicles RequestedVehicle {
            get {
                return this.RequestedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedVehicleField, value) != true)) {
                    this.RequestedVehicleField = value;
                    this.RaisePropertyChanged("RequestedVehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedVehicles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentedVehicles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RentIdField;
        
        private int RentedVehicleIdField;
        
        private int SupplierCompanyIdField;
        
        private int DriverCustomerIdField;
        
        private System.DateTime PickUpDateField;
        
        private System.DateTime DropOffDateField;
        
        private int VehiclesPickUpKmField;
        
        private int VehiclesDropOffKmField;
        
        private decimal RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Customers DriverCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Vehicles RentedVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.Companies SupplierCompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentId {
            get {
                return this.RentIdField;
            }
            set {
                if ((this.RentIdField.Equals(value) != true)) {
                    this.RentIdField = value;
                    this.RaisePropertyChanged("RentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RentedVehicleId {
            get {
                return this.RentedVehicleIdField;
            }
            set {
                if ((this.RentedVehicleIdField.Equals(value) != true)) {
                    this.RentedVehicleIdField = value;
                    this.RaisePropertyChanged("RentedVehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierCompanyId {
            get {
                return this.SupplierCompanyIdField;
            }
            set {
                if ((this.SupplierCompanyIdField.Equals(value) != true)) {
                    this.SupplierCompanyIdField = value;
                    this.RaisePropertyChanged("SupplierCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DriverCustomerId {
            get {
                return this.DriverCustomerIdField;
            }
            set {
                if ((this.DriverCustomerIdField.Equals(value) != true)) {
                    this.DriverCustomerIdField = value;
                    this.RaisePropertyChanged("DriverCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DropOffDate {
            get {
                return this.DropOffDateField;
            }
            set {
                if ((this.DropOffDateField.Equals(value) != true)) {
                    this.DropOffDateField = value;
                    this.RaisePropertyChanged("DropOffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehiclesPickUpKm {
            get {
                return this.VehiclesPickUpKmField;
            }
            set {
                if ((this.VehiclesPickUpKmField.Equals(value) != true)) {
                    this.VehiclesPickUpKmField = value;
                    this.RaisePropertyChanged("VehiclesPickUpKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int VehiclesDropOffKm {
            get {
                return this.VehiclesDropOffKmField;
            }
            set {
                if ((this.VehiclesDropOffKmField.Equals(value) != true)) {
                    this.VehiclesDropOffKmField = value;
                    this.RaisePropertyChanged("VehiclesDropOffKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Customers DriverCustomer {
            get {
                return this.DriverCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverCustomerField, value) != true)) {
                    this.DriverCustomerField = value;
                    this.RaisePropertyChanged("DriverCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Vehicles RentedVehicle {
            get {
                return this.RentedVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehicleField, value) != true)) {
                    this.RentedVehicleField = value;
                    this.RaisePropertyChanged("RentedVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Companies SupplierCompany {
            get {
                return this.SupplierCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCompanyField, value) != true)) {
                    this.SupplierCompanyField = value;
                    this.RaisePropertyChanged("SupplierCompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CustomerPhoneNumber {
            get {
                return this.CustomerPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNumberField, value) != true)) {
                    this.CustomerPhoneNumberField = value;
                    this.RaisePropertyChanged("CustomerPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SecondPhoneNumber {
            get {
                return this.SecondPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondPhoneNumberField, value) != true)) {
                    this.SecondPhoneNumberField = value;
                    this.RaisePropertyChanged("SecondPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NationalIdcard {
            get {
                return this.NationalIdcardField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdcardField, value) != true)) {
                    this.NationalIdcardField = value;
                    this.RaisePropertyChanged("NationalIdcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentalRequests[] RentalRequests {
            get {
                return this.RentalRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalRequestsField, value) != true)) {
                    this.RentalRequestsField = value;
                    this.RaisePropertyChanged("RentalRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CarRentalManagementSystem.Web.EmployeeWebService.RentedVehicles[] RentedVehicles {
            get {
                return this.RentedVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.RentedVehiclesField, value) != true)) {
                    this.RentedVehiclesField = value;
                    this.RaisePropertyChanged("RentedVehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeWebService.EmployeesWebServiceSoap")]
    public interface EmployeesWebServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsEmployee", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse SignUpAsEmployee(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUpAsEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse> SignUpAsEmployeeAsync(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki email öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsEmployee", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse LogInAsEmployee(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogInAsEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse> LogInAsEmployeeAsync(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployeeAccount", ReplyAction="*")]
        bool DeleteEmployeeAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployeeAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAccountAsync(int id);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki entity öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse UpdateAccount(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetAllEmployeesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse GetAllEmployees(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse> GetAllEmployeesAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetEmployeeInformationByIDResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeInformationByID", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse GetEmployeeInformationByID(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeInformationByID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse> GetEmployeeInformationByIDAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetCompanysAllEmployeesResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllEmployees", ReplyAction="*")]
        CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse GetCompanysAllEmployees(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanysAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse> GetCompanysAllEmployeesAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAsEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequestBody Body;
        
        public SignUpAsEmployeeRequest() {
        }
        
        public SignUpAsEmployeeRequest(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAsEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees entity;
        
        public SignUpAsEmployeeRequestBody() {
        }
        
        public SignUpAsEmployeeRequestBody(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpAsEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpAsEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponseBody Body;
        
        public SignUpAsEmployeeResponse() {
        }
        
        public SignUpAsEmployeeResponse(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpAsEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignUpAsEmployeeResult;
        
        public SignUpAsEmployeeResponseBody() {
        }
        
        public SignUpAsEmployeeResponseBody(bool SignUpAsEmployeeResult) {
            this.SignUpAsEmployeeResult = SignUpAsEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequestBody Body;
        
        public LogInAsEmployeeRequest() {
        }
        
        public LogInAsEmployeeRequest(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInAsEmployeeRequestBody() {
        }
        
        public LogInAsEmployeeRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInAsEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInAsEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponseBody Body;
        
        public LogInAsEmployeeResponse() {
        }
        
        public LogInAsEmployeeResponse(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInAsEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInAsEmployeeResult;
        
        public LogInAsEmployeeResponseBody() {
        }
        
        public LogInAsEmployeeResponseBody(bool LogInAsEmployeeResult) {
            this.LogInAsEmployeeResult = LogInAsEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccount", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequestBody Body;
        
        public UpdateAccountRequest() {
        }
        
        public UpdateAccountRequest(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees entity;
        
        public UpdateAccountRequestBody() {
        }
        
        public UpdateAccountRequestBody(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponseBody Body;
        
        public UpdateAccountResponse() {
        }
        
        public UpdateAccountResponse(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateAccountResult;
        
        public UpdateAccountResponseBody() {
        }
        
        public UpdateAccountResponseBody(bool UpdateAccountResult) {
            this.UpdateAccountResult = UpdateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequestBody Body;
        
        public GetAllEmployeesRequest() {
        }
        
        public GetAllEmployeesRequest(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeesRequestBody {
        
        public GetAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponseBody Body;
        
        public GetAllEmployeesResponse() {
        }
        
        public GetAllEmployeesResponse(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetAllEmployeesResult;
        
        public GetAllEmployeesResponseBody() {
        }
        
        public GetAllEmployeesResponseBody(CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetAllEmployeesResult) {
            this.GetAllEmployeesResult = GetAllEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeInformationByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeInformationByID", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequestBody Body;
        
        public GetEmployeeInformationByIDRequest() {
        }
        
        public GetEmployeeInformationByIDRequest(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeInformationByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetEmployeeInformationByIDRequestBody() {
        }
        
        public GetEmployeeInformationByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeInformationByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeInformationByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponseBody Body;
        
        public GetEmployeeInformationByIDResponse() {
        }
        
        public GetEmployeeInformationByIDResponse(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeInformationByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees GetEmployeeInformationByIDResult;
        
        public GetEmployeeInformationByIDResponseBody() {
        }
        
        public GetEmployeeInformationByIDResponseBody(CarRentalManagementSystem.Web.EmployeeWebService.Employees GetEmployeeInformationByIDResult) {
            this.GetEmployeeInformationByIDResult = GetEmployeeInformationByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequestBody Body;
        
        public GetCompanysAllEmployeesRequest() {
        }
        
        public GetCompanysAllEmployeesRequest(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllEmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyid;
        
        public GetCompanysAllEmployeesRequestBody() {
        }
        
        public GetCompanysAllEmployeesRequestBody(int companyid) {
            this.companyid = companyid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanysAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanysAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponseBody Body;
        
        public GetCompanysAllEmployeesResponse() {
        }
        
        public GetCompanysAllEmployeesResponse(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanysAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetCompanysAllEmployeesResult;
        
        public GetCompanysAllEmployeesResponseBody() {
        }
        
        public GetCompanysAllEmployeesResponseBody(CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetCompanysAllEmployeesResult) {
            this.GetCompanysAllEmployeesResult = GetCompanysAllEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeesWebServiceSoapChannel : CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesWebServiceSoapClient : System.ServiceModel.ClientBase<CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap>, CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap {
        
        public EmployeesWebServiceSoapClient() {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.SignUpAsEmployee(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest request) {
            return base.Channel.SignUpAsEmployee(request);
        }
        
        public bool SignUpAsEmployee(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).SignUpAsEmployee(inValue);
            return retVal.Body.SignUpAsEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.SignUpAsEmployeeAsync(CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest request) {
            return base.Channel.SignUpAsEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeResponse> SignUpAsEmployeeAsync(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.SignUpAsEmployeeRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).SignUpAsEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.LogInAsEmployee(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest request) {
            return base.Channel.LogInAsEmployee(request);
        }
        
        public bool LogInAsEmployee(string email, string password) {
            CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).LogInAsEmployee(inValue);
            return retVal.Body.LogInAsEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.LogInAsEmployeeAsync(CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest request) {
            return base.Channel.LogInAsEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeResponse> LogInAsEmployeeAsync(string email, string password) {
            CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.LogInAsEmployeeRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).LogInAsEmployeeAsync(inValue);
        }
        
        public bool DeleteEmployeeAccount(int id) {
            return base.Channel.DeleteEmployeeAccount(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAccountAsync(int id) {
            return base.Channel.DeleteEmployeeAccountAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.UpdateAccount(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public bool UpdateAccount(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).UpdateAccount(inValue);
            return retVal.Body.UpdateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.UpdateAccountAsync(CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountResponse> UpdateAccountAsync(CarRentalManagementSystem.Web.EmployeeWebService.Employees entity) {
            CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.UpdateAccountRequestBody();
            inValue.Body.entity = entity;
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).UpdateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetAllEmployees(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployees(request);
        }
        
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetAllEmployees() {
            CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequestBody();
            CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetAllEmployees(inValue);
            return retVal.Body.GetAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetAllEmployeesAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesResponse> GetAllEmployeesAsync() {
            CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetAllEmployeesRequestBody();
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetEmployeeInformationByID(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest request) {
            return base.Channel.GetEmployeeInformationByID(request);
        }
        
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees GetEmployeeInformationByID(int id) {
            CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequestBody();
            inValue.Body.id = id;
            CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetEmployeeInformationByID(inValue);
            return retVal.Body.GetEmployeeInformationByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetEmployeeInformationByIDAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest request) {
            return base.Channel.GetEmployeeInformationByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDResponse> GetEmployeeInformationByIDAsync(int id) {
            CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetEmployeeInformationByIDRequestBody();
            inValue.Body.id = id;
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetEmployeeInformationByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetCompanysAllEmployees(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest request) {
            return base.Channel.GetCompanysAllEmployees(request);
        }
        
        public CarRentalManagementSystem.Web.EmployeeWebService.Employees[] GetCompanysAllEmployees(int companyid) {
            CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequestBody();
            inValue.Body.companyid = companyid;
            CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse retVal = ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetCompanysAllEmployees(inValue);
            return retVal.Body.GetCompanysAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse> CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap.GetCompanysAllEmployeesAsync(CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest request) {
            return base.Channel.GetCompanysAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesResponse> GetCompanysAllEmployeesAsync(int companyid) {
            CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest inValue = new CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequest();
            inValue.Body = new CarRentalManagementSystem.Web.EmployeeWebService.GetCompanysAllEmployeesRequestBody();
            inValue.Body.companyid = companyid;
            return ((CarRentalManagementSystem.Web.EmployeeWebService.EmployeesWebServiceSoap)(this)).GetCompanysAllEmployeesAsync(inValue);
        }
    }
}
